pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'docker ps'
                sh 'curl http://localhost:5000/'
            }
        }
    }

    post {
        success {
            echo 'Student Result Management System deployed successfully!'
        }

        failure {
            echo 'Deployment failed.'
        }
    }
}