pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Verify Deployment') {
    steps {
        sh 'docker ps'
        sh 'docker inspect -f "{{.State.Running}}" student-backend'
        sh 'docker inspect -f "{{.State.Running}}" student-frontend'
    }
}
    }

    post {
        success {
            echo 'Student Result Management System deployed successfully!'
        }

        failure {
            echo 'Deployment failed.'
        }
    }
}